version: "3"
services:
  django-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-server
    container_name: "django-server"
    environment:
      - DJANGO_ENV
    volumes:
      - .:/root/django-app
      - ../vue-boilerplate/dist:/root/vue-app/dist
    network_mode: "host"
    command: python manage.py runserver
  postgres:
    container_name: $POSTGRES_CONTAINER_NAME
    image: 'postgres:12.4'
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - $POSTGRES_MOUNTED_VOLUME:/var/lib/postgresql/data
  postgres_test:
    container_name: $POSTGRES_CONTAINER_NAME
    image: 'postgres:12.4'
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - $POSTGRES_MOUNTED_VOLUME:/var/lib/postgresql/data
