version: "3"
services:
  postgres:
    container_name: $POSTGRES_CONTAINER_NAME
    image: 'postgres:12.4'
    restart: always
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - $POSTGRES_MOUNTED_VOLUME:/var/lib/postgresql/data
